### ISSUE TITLE
Slack Tokens Leaked

### ISSUE THREAD

**Issue by jamescmartinez** [BrandonShega/.spacemacs.d#1]
I received a message from Slack that you've leaked a token and it's been automatically disabled. I'd imagine the admins of the other Slack teams have received the same notification.

https://github.com/BrandonShega/.spacemacs.d/blob/master/layers/personal/local/personal/personal.el

**Comment by BrandonShega** [comment]
Thanks! I removed the tokens and commits referencing them.
